Add test for smart table and login (Homework #13)
isakawar/ngx-cypress-test pull request #3
Opened 2023-12-02 23:10 UTC by isakawar

**Pull Request Description:**

**Changes in the Pull Request:**

1. **Added tests for Smart Table page:**
2. **Created tests for authentication:**
3. **Added a custom login command:**

2023-12-02 23:15 UTC, isakawar commented on cypress/common/pages/loginPage.js
Упс, це зайве, я тут планував реалізувати верифікація, але щось забувся, реалізую в некст тайм

2023-12-02 23:16 UTC, isakawar commented on cypress.env.json
Я розумію, що креденшени зберігати в гіті - ред флег, це просто для наглядності)

2023-12-03 11:13 UTC, sttaran requested changes

2023-12-03 11:13 UTC, sttaran commented on cypress/common/enums/tablesAndDataPageLocators.js
> +}
no need to store selectors in other file. Move it to page object

2023-12-03 11:13 UTC, sttaran commented on cypress/e2e/tests/testSmartTable.js
> +  })
create another describe for this test

2023-12-03 15:39 UTC, sttaran requested changes

2023-12-03 15:39 UTC, sttaran commented on cypress/e2e/tests/testSmartTable.js
> +  })
move it to separated describe

2023-12-20 12:44 UTC, merged